spring.application.name=corporate-training-system
spring.datasource.url=jdbc:mysql://localhost:3306/corporate_training_system
spring.datasource.username=root
spring.datasource.password=Anamika@6020
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true